---
project:
  type: website

lang: tr

website:
  title: "İbrahim ÇAPAR"
  site-url: "https://ibrahimcapar.com"
  

  navbar:
    left:
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projelerim
    
    right:
      - icon: linkedin
        href: https://linkedin.com/in/ibrahimcapar1
        target: _blank
      - icon: envelope-fill
        href: "mailto:ibrahimcaparr1@gmail.com"

format:
  html:
    link-external-newwindow: true
    theme: litera
    css: styles.css
    toc: true 

execute:
  freeze: auto
...