---
project:
  type: website

lang: tr

website:
  title: "İbrahim ÇAPAR"
  site-url: "https://ibrahimcapar.com"
  google-analytics: "G-SRL55MJHF7"
  

  navbar:
    left:
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projelerim
    
    right:
      - icon: linkedin
        href: https://linkedin.com/in/ibrahimcapar1
        target: _blank
      - icon: envelope-fill
        href: "mailto:ibrahimcaparr1@gmail.com"

format:
  html:
    code-overflow: wrap
    link-external-newwindow: true
    theme: darkly #flatly #litera
    css: styles.css
    toc: true 
    highlight-style: dracula

execute:
  freeze: auto

mainfont: "Inter"   
fontsize: 1.0em      
linestretch: 1.6   

lightbox:
  effect: fade
  desc-position: bottom
  loop: true
...