---
project:
  type: website

website:
  title: "İbrahim ÇAPAR"
  site-url: "https://ibrahimcapar.com"
  

  navbar:
    left:
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projelerim
    
    right:
      - icon: linkedin
        href: https://linkedin.com/in/ibrahimcapar1
      - icon: envelope-fill
        href: "mailto:ibrahimcaparr1@gmail.com"

format:
  html:
    theme: litera
    css: styles.css
    toc: true 
    link-external-newwindow: true
...